# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: LenNX-Laptop
  demands:
   - agent.name -equals DESKTOP-L8PEL36

steps:
- script: mvn --version
  displayName: 'Run a one-line script'
